language: python
python:
  - "3.9"

services:
  - docker

before_script: pip install docker-compose tox coverage django-nose

script:
  - docker-compose run --rm app sh -c "./manage.py test && flake8"
