language: python
python:
  - "3.9"

services:
  - docker

before_install:
  - chmod 755 /app

before_script: pip install docker-compose coverage django-nose

script:
  - docker-compose run --rm app sh -c "./manage.py test && flake8"
